name: sim_absensi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.3
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  dio: ^5.4.3
  get: ^4.6.6
  image_picker: ^1.0.7
  flutter_screenutil: ^5.9.0
  geolocator: ^11.0.0
  easy_localization: ^3.0.3
  flutter_image_compress: ^2.1.0
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/onboarding/
    - assets/fonts/Poppins-Black.ttf
    - assets/fonts/Poppins-Bold.ttf
    - assets/fonts/Poppins-ExtraBold.ttf
    - assets/fonts/Poppins-Light.ttf
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Poppins-SemiBold.ttf
