// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoWRc0YZytZKSQy5o93-O8dGAJZYlswI8',
    appId: '1:488654596208:web:7659eb091ba05062466cb5',
    messagingSenderId: '488654596208',
    projectId: 'absensi-d0891',
    authDomain: 'absensi-d0891.firebaseapp.com',
    storageBucket: 'absensi-d0891.firebasestorage.app',
    measurementId: 'G-1JDE5ZLKKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD49mWspRra6C2KBnGLLfiAlLhbR0foClI',
    appId: '1:488654596208:android:56e611395d0cbf47466cb5',
    messagingSenderId: '488654596208',
    projectId: 'absensi-d0891',
    storageBucket: 'absensi-d0891.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Q_EQskSASABXSiKQHdDc3RyVb40ow5g',
    appId: '1:488654596208:ios:225d9b4cb9c9d67a466cb5',
    messagingSenderId: '488654596208',
    projectId: 'absensi-d0891',
    storageBucket: 'absensi-d0891.firebasestorage.app',
    iosBundleId: 'com.example.simAbsensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Q_EQskSASABXSiKQHdDc3RyVb40ow5g',
    appId: '1:488654596208:ios:225d9b4cb9c9d67a466cb5',
    messagingSenderId: '488654596208',
    projectId: 'absensi-d0891',
    storageBucket: 'absensi-d0891.firebasestorage.app',
    iosBundleId: 'com.example.simAbsensi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoWRc0YZytZKSQy5o93-O8dGAJZYlswI8',
    appId: '1:488654596208:web:951ee91a8dda311c466cb5',
    messagingSenderId: '488654596208',
    projectId: 'absensi-d0891',
    authDomain: 'absensi-d0891.firebaseapp.com',
    storageBucket: 'absensi-d0891.firebasestorage.app',
    measurementId: 'G-55YK92GCX2',
  );
}
